set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_FIXUP_ELF_RPATH ON)

if(PORT STREQUAL "joltphysics")
  set(VCPKG_CXX_FLAGS "-DJPH_FLOATING_POINT_EXCEPTIONS_ENABLED")
  set(VCPKG_C_FLAGS "")
endif()
